### ISSUE TITLE
prepare.sh return error

### ISSUE THREAD

**Issue by vacher** [zilliztech/phantoscope#120] opened 2020-06-30 02:38 UTC
我的执行步骤
**1.下载 Phantoscope**
git clone https://github.com/zilliztech/phantoscope.git -b 0.1.0
cd phantoscope

**2.设置环境变量**
$ export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)

**3.启动 Phantoscope 容器：**
$ sudo docker-compose up -d

**4.检查所有容器状态**
$ sudo docker-compose ps
Ok

**5.创建pipeline**
chmod +x scripts/prepare.sh
 ./scripts/prepare.sh

**这儿返回了错误：**
{"message": "opeartor vgg16 regist error", "error": "OperatorRegistError"}{"message": "query from sql error", "error": "QueryFromSQLError"}{"message": "query from sql error", "error": "QueryFromSQLError"}

**Comment by ReigenAraka** [comment] 2020-07-01 01:57
Follow those steps:
1. `docker-compose down`
2. `docker-compose up -d`
3. `./scripts/prepare.sh`

can you paste your `docker info`?

**Comment by vacher** [comment] 2020-07-01 09:43
**执行后的返回值**
{"_name": "vgg16", "_backend": "vgg16", "_type": "encoder", "_input": "image", "_output": "vector", "_endpoint": ":50001", "_metric_type": "L2", "_dimension": 512}{"_pipeline_name": "example_pipeline", "_input": "image", "_output": "vector", "_dimension": 512, "_index_file_size": 1024, "_metric_type": "L2", "_pipeline_description": "pipeline example", "_processors": [""], "_encoder": "vgg16", "_description": "pipeline example"}{"message": "There has some error when create s3 buckets", "error": "S3Error"}

**docker info信息**

Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 5
  Paused: 0
  Stopped: 8
 Images: 59
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-59-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.56GiB
 Name: dssy-HP
 ID: PNCA:W6DA:YEZU:WITU:CXZG:UV3W:LGTA:E2EE:M6RT:HVB6:7XEW:WCJI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by ABNER-1** [comment] 2020-07-01 13:56
Did you run `export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)` command in this shell? Or run in the previous shell terminator?
This error is always caused by this.
try these steps to fix it, or delete all to rerun quick start.
```shell
$ export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)
$ docker-compose down
$ docker-compose up -d
$ ./scripts/prepare.sh # ignore other errors if you create application successfully in this command
```

**Comment by gachiemchiep** [comment] 2020-07-06 00:02
@ABNER-1 

Hello. I re-try your steps but met the same error.

```bash
(base) gachiemchiep:phantoscope$ export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)
(base) gachiemchiep:phantoscope$ docker-compose down
Removing network phantoscope_default
WARNING: Network phantoscope_default not found.
(base) gachiemchiep:phantoscope$ docker-compose up -d
Creating network "phantoscope_default" with the default driver
Creating phantoscope_milvus_1 ... done
Creating phantoscope_mongo_1  ... done
Creating phantoscope_minio_1  ... done
Creating phantoscope_mysql_1  ... done
Creating phantoscope_api_1    ... done
Creating phantoscope_vgg_1    ... done
(base) gachiemchiep:phantoscope$ ./scripts/prepare.sh
{"message": "opeartor vgg16 regist error", "error": "OperatorRegistError"}{"message": "query from sql error", "error": "QueryFromSQLError"}{"message": "query from sql error", "error": "QueryFromSQLError"}(base)

```

**Comment by gachiemchiep** [comment] 2020-07-06 00:26
Hello @ABNER-1 

Look like the API did change 12 days ago from **/regist** to **/register** at https://github.com/zilliztech/phantoscope/commit/ae40729f8d7e856de9baa213fcb60c6ab6b7d1cb. But the document is still using the old API. 
Would you guys mind updating the document to newest version?

**Comment by ABNER-1** [comment] 2020-07-06 01:27
Hello @gachiemchiep
Yeah, you are right. We did some api changes during 0.2.0. 
So, we recommand to checkout 0.1.0 branch to use until the publish of 0.2.0.
Of course, we are changing all docs in the next days to prepare the publish of 0.2.0.
Thanks for your issue to point out this.

**Comment by vacher** [comment] 2020-07-06 03:21
换了一台新机子，重新配置的
执行  ./scripts/prepare.sh 后返回

{"_name": "vgg16", "_backend": "vgg16", "_type": "encoder", "_input": "image", "_output": "vector", "_                                                  endpoint": ":50001", "_metric_type": "L2", "_dimension": 512}{"_pipeline_name": "example_pipeline", "_                                                  input": "image", "_output": "vector", "_dimension": 512, "_index_file_size": 1024, "_metric_type": "L2                                                  ", "_pipeline_description": "pipeline example", "_processors": [""], "_encoder": "vgg16", "_descriptio                                                  n": "pipeline example"}{"message": "There has some error when create s3 buckets", "error": "S3Error"}

这个算ok么？好像还是有些error

**Comment by ABNER-1** [comment] 2020-07-06 06:52
This is not machine problem.  
You may execute `docker-compose up -d` without running command`export export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)` before.

Please ensure you run in the same teminator shell.

**Comment by vacher** [comment] 2020-07-06 08:13
thank you！
我全部切换到root账户下执行了一遍可以了
可能是因为 docker-compose up -d 我加了sudo
而export  是当前用户

**Comment by ABNER-1** [comment] 2020-07-06 11:54
Happy for you. I will close this issue.

**Closed by ABNER-1** 2020-07-06 11:54 UTC
Labels: documentation
