### ISSUE TITLE
0.1.0 doesn't creat database when api server start

### ISSUE THREAD

**Issue by ReigenAraka** [zilliztech/phantoscope#101] opened 2020-06-17 08:25 UTC
**Describe the bug**
api server not creat database correctly

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
- Phantoscope version (v0.1.0)
- wsl 2.0

**Screenshots**

**Additional context**

**Comment by ReigenAraka** [comment] 2020-07-01 01:59
#120

**Comment by ijackwu** [comment] 2020-07-14 09:18
try agent
```bash

git checkout 0.1.0

rm /mnt/om

```

**Comment by ABNER-1** [comment] 2020-07-30 02:59
It is usually caused by run scripts quickly when docker-compose ok. 
Wait for some seconds or restart docker-compose container maybe help.
Close this issue.

**Closed by ABNER-1** 2020-07-30 02:59 UTC
Labels: bug
